# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: app_db
    user: app_user
    secureJsonData:
      password: ${PG_APP_PWD}
    jsonData:
      sslmode: 'disable'