{
 "title": "Telco Customer Chrurn",
 "time": { "from": "2024-09-21T00:01:23.000Z", "to": "2024-09-27T00:01:39.000Z" },
 "panels": [
  {
   "title": "Predictions per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_date, COUNT(1) Qty\r\nFROM public.prediction_logs\r\nGROUP BY prediction_date"
    }
   ]
  },
  {
   "title": "Predictions by Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_date\r\n\t,CASE prediction\r\n\t\tWHEN 1 THEN 'Churn'\r\n\t\tELSE 'Not Churn'\r\n\tEND Prediction\r\n\t,COUNT(1) Qty\r\nFROM public.prediction_logs\r\nGROUP BY prediction_date, prediction"
    }
   ]
  },
  {
   "title": "Data Drift per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date_dataset, AVG(drift_score) AVG_Drift\r\nFROM public.data_columns_report\r\nGROUP BY date_dataset"
    }
   ]
  },
  {
   "title": "Drift Report",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date_dataset, number_of_drifted_columns, share_of_drifted_columns\r\nFROM public.data_report"
    }
   ]
  }
 ]
}